config/routes.rb
Rails.application.routes.draw do
  namespace :concerns do
    get 'clans/index'
  end

	require 'sidekiq/web'
	mount Sidekiq::Web => '/sidekiq', as: :sidekiq

	root 'clans#home'
	get 'search' => 'search#index', as: :search

	resources :clans, only: [:index, :show] do
		get :stats, on: :member
		get :members, on: :member
		get :tanks, on: :member
		get :changes, on: :member
  end

  resources :players, only: :show
end

app/models/clan.rb
class Clan < ActiveRecord::Base
	self.per_page = 20

	has_many :members, class_name: :Player
	has_many :player_tanks, through: :members
	has_many :tanks, through: :player_tanks
	has_many :player_stats, through: :members

	enum status: {
				 ok: 1
			 }

	def needs_update?
		Time.zone.now - updated_at > 2.hours || members.count > 100
	end

	def current_player_stats
		@current_player_stats ||= player_stats.select('DISTINCT ON (player_id) *').order('player_id, player_stats.created_at DESC').to_a
	end

	def self.find_or_load(id, force_load: false)
		clan = self.find_by id: id
		if clan.nil? || force_load || clan.needs_update?
			api_data =  self.load_data_from_api(id)
			clan = self.create!(id: id) if clan.nil?
			clan.update!({status: :ok}.merge(api_data[:clan]))
			clan.touch
			clan.update_players(api_data[:members])
		end
		clan
	end

	def self.load_data_from_api(id)
		Rails.logger.info "Updating clan #{id} from API"
		response = WargamingApi.new(Regions.from_id(id)).clan_info([id]).parsed_response
		data = response['data'][id.to_s]
		{
			clan: {
				name: data['name'],
				tag: data['abbreviation'],
				motto: data['motto'],
				description: data['description_html']
			}, members: data['members'].map { |aid, row| {id: aid, name: row['account_name'], role: row['role']} }
		}
	end

	def update_players(members_data)
		Player.transaction do
			members_data.each do |player_data|
				player = Player.find_or_create_by!(id: player_data[:id])
				player.update!({status: :ok, clan_id: id}.merge(player_data))
			end

			members.each do |member|
				member.update_attribute(:clan_id, 0) unless members_data.any? { |md| md[:id].to_i == member.id }
			end
		end

		members.reload
	end
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :player_tanks
  has_many :tanks, through: :player_tanks
  has_many :player_stats
  belongs_to :clan

  enum status: {
         ok: 1
       }

  enum role: {
         leader: 'leader',
         vice_leader: 'vice_leader',
         junior_officer: 'junior_officer',
         soldier: 'private',
         personnel_officer: 'personnel_officer',
         diplomat: 'diplomat',
         recruiter: 'recruiter',
         reservist: 'reservist',
         recruit: 'recruit',
         commander: 'commander',
         treasurer: 'treasurer'
       }

  def current_stats
    player_stats.order(created_at: :desc).first
  end

  def update_tanks(tanks_data)
    to_insert = []
    to_update = {}

    tanks_data.each do |tank_data|
      player_tank = player_tanks.detect { |pt| pt.tank_id == tank_data['tank_id'] }
      if player_tank.nil?
        to_insert << [tank_data['tank_id'], id, tank_data['statistics']['wins'], tank_data['statistics']['battles'], tank_data['mark_of_mastery']]
      elsif player_tank.battles < tank_data['statistics']['battles']
        to_update[player_tank.id] = {
          wins: tank_data['statistics']['wins'],
          battles: tank_data['statistics']['battles'],
          mark_of_mastery: tank_data['mark_of_mastery']
        }
      end
    end

    PlayerTank.import [:tank_id, :player_id, :wins, :battles, :mark_of_mastery], to_insert
    PlayerTank.update to_update.keys, to_update.values
  end

  def update_stats(stats_data)
    player_stats.create!({
      battles: stats_data['statistics']['all']['battles'],
      wins: stats_data['statistics']['all']['wins'],
      defeats: stats_data['statistics']['all']['losses'],
      survived: stats_data['statistics']['all']['survived_battles'],
      frags: stats_data['statistics']['all']['frags'],
      spotted: stats_data['statistics']['all']['spotted'],
      accuracy: stats_data['statistics']['all']['hits'].to_f / stats_data['statistics']['all']['shots'],
      damage: stats_data['statistics']['all']['damage_dealt'],
      capture: stats_data['statistics']['all']['capture_points'],
      defense: stats_data['statistics']['all']['dropped_capture_points'],
      experience: stats_data['statistics']['all']['base_xp']
    })
  end
end

app/models/player_stat.rb
class PlayerStat < ActiveRecord::Base
  belongs_to :player
end

app/models/player_tank.rb
class PlayerTank < ActiveRecord::Base
  belongs_to :player
  belongs_to :tank
end

app/models/tank.rb
class Tank < ActiveRecord::Base
  enum tank_type: {
         heavy: 'heavyTank',
         medium: 'mediumTank',
         light: 'lightTank',
         td: 'AT-SPG',
         arty: 'SPG'
       }

  enum nation: {
         ussr: 'ussr',
         usa: 'usa',
         uk: 'uk',
         germany: 'germany',
         china: 'china',
         japan: 'japan',
         france: 'france'
       }

  scope :top, -> { where(level: 10) }
  scope :top_scout, -> { where(level: 8).light }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	before_action :setup_locals

	protected

	def current_region
		@locals[:region]
	end

	private

	def setup_locals
		@locals = {}

		region = (params[:region] || cookies[:region] || 1).to_i
		region = 1 if Regions::SUPPORTED_REGIONS[region].nil?
		cookies[:region] = { value: region, expires: 1.year.from_now } if cookies[:region] != region
		@locals[:region] = region
	end
end

app/controllers/clan_events_controller.rb
class ClanEventsController < WebsocketRails::BaseController
  def load
		ClanUpdaterWorker.perform_async(1, [message.to_i])
  end
end

app/controllers/clans_controller.rb
class ClansController < ApplicationController

	before_action :load_clan, only: [:show, :stats, :members, :tanks, :changes]
	before_action :setup_clan_locals, except: :home

	def home
	end

  def index
		@clans = Clan.paginate(page: params[:page])
	end

	def show
		@member_view = ClanMemberView.new(@clan)
		@stat_view = ClanStatView.new(@clan)
		@tank_view = ClanTankView.new(@clan)
	end

	def stats
		@stat_view = ClanStatView.new(@clan)
	end

	def members
	end


	def tanks
	end


	def changes
	end

	private

	def load_clan
		@clan = Clan.find_or_load(params[:id].to_i, force_load: params[:force].present?)
		@locals[:title] = @clan.tag
	end

	def setup_clan_locals
		@locals[:nav_item] = :clans
	end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

	before_action :load_player, only: [:show]

	def show
	end

	private

	def load_player
		@player = Player.find_or_create_by(id: params[:id])
	end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	def index
		response = WargamingApi.new(current_region).clan_search(params[:search]).parsed_response
		if response['error'].present?
			@clans = []
			@locals[:error] = response['error']['message']
		else
			@clans = response['data']
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title
		@locals[:title].present? ? "WoTcs | #{@locals[:title]}" : 'WoTcs | Clan and player statistics'
	end

	def current_region
		@locals[:region]
	end

	def current_region_humanized
		Regions::SUPPORTED_REGIONS[current_region]
	end

	def nav_item
		@locals[:nav_item] || nil
	end
end

app/helpers/clans_helper.rb
module ClansHelper
	def members_name_badge(members)
		if members.any?
			content_tag('span', class: 'badge', title: members.map(&:name).join(', ')) do
				"#{members.first.name}" + (members.count > 1 ? " and #{members.count - 1} more" : '')
			end
		end
	end
end

app/helpers/concerns/clans_helper.rb
module Concerns::ClansHelper
end

app/views/clans/_clan_top.haml
.row.ad-container-300x250
	#clan_header.ad-rest.col-padding-left
		%h1
			= image_tag Regions.emblem_url(@clan.id)
			[#{@clan.tag}]
		%h2= @clan.name
		%em= @clan.motto

		%ul.nav.nav-tabs.hidden-xxs.hidden-xs.hidden-sm
			= render 'nav_tabs', active: active

	.ad-column
		.ad.float
		#clan_description_small.visible-sm.col-padding
			= render 'side_column'

.row-fluid.visible-xs.visible-sm
	.span12
		%ul.nav.nav-tabs
			= render 'nav_tabs', active: active

app/views/clans/_nav_tabs.haml
%li{class: active == :home ? 'active' : ''}
	= link_to 'Home', @clan
%li{class: active == :stats ? 'active' : ''}
	= link_to 'Stats', [:stats, @clan]
%li{class: active == :members ? 'active' : ''}
	= link_to 'Members', [:members, @clan]
%li{class: active == :tanks ? 'active' : ''}
	= link_to 'Tanks', [:tanks, @clan]
%li{class: active == :changes ? 'active' : ''}
	= link_to 'Changes', [:changes, @clan]
	

app/views/clans/_side_column.haml
%h3 Description
= @clan.description.html_safe

app/views/clans/changes.haml
- @locals[:title] += ' - Changes'
= render 'clan_top', active: :changes

app/views/clans/home.haml
%h1.text-center A simple tool, which will show you battle potential of your enemy

%form.form-inline.main-search-form.text-center{action: search_path, method: 'get'}
	= hidden_field_tag :region, current_region
	= render 'partials/region_dropdown', class_name: 'text-left'
	.form-group.wide
		= text_field_tag :search, '', autofocus: true, placeholder: 'Search for a clan or player', class: 'form-control'
	%button.btn Search

.row.ad-container-300x250
	.ad-rest
		.main-logo
			.yellow-line-wrapper
				.yellow-line
			%p.logo-text
				= image_tag 'logo-text.png', class: 'pull-left'
				%br
				WoTcs.com was created when Clan Wars were first introduced. It allows you to check your opponent's strength
				without having to browse each clan's members' profile. You can read more about this project
				= link_to 'here', '#'

		.news-container
			%h2 News
			.news-element
				%h3
					Testing version online
					%small 20/03/2014
				%p
					So I decided to share with you what I am working on. Right now there isn't much to see, but
					new updates should follow soon. All comments and feedback are highly appreciated.
	.ad-column
		.ad

app/views/clans/home/_changes.haml
.stats-switch.js-switch
	= link_to 'All', '#', class: 'active'
	= '/'
	= link_to 'Joined', '#'
	= '/'
	= link_to 'Left', '#'

- last_changes = [{joined: true, player_name: 'player1', changed_at: '01/11/14'},{joined: false, player_name: 'player2', changed_at: '01/11/14'},{joined: true, player_name: 'player3', changed_at: '12/11/14'},{joined: true, player_name: 'player4', changed_at: '15/11/14'},{joined: false, player_name: 'player5', changed_at: '28/11/14'}]
.list-group.list-group-small
	- last_changes.reverse.each do |change|
		%a.list-group-item{href: '#', class: "list-group-item-#{change[:joined] ? 'success' : 'danger'}"}
			= change[:player_name]
			%span.badge= change[:changed_at]

app/views/clans/home/_members.haml
.stats-switch
	%strong= @member_view.count
	= "(#{@member_view.count(:soldier)} Privates and #{@member_view.count(:recruit)} Recruits)"

.list-group.list-group-small
	%a.list-group-item{href: '#'}
		%span.hidden-xs Clan Commander
		%span.visible-xs C:
		- if @member_view.has_members?
			%span.badge= @member_view.leader.name
	%a.list-group-item{href: '#'}
		%span.hidden-xs Executive Officer(s)
		%span.visible-xs EO:
		= members_name_badge(@member_view.vice_leaders)
	%a.list-group-item{href: '#'}
		%span.hidden-xs Combat Officers(s)
		%span.visible-xs CO:
		= members_name_badge(@member_view.commanders)
	%a.list-group-item{href: '#'}
		%span.hidden-xs Intelligence Officer(s)
		%span.visible-xs IO:
		= members_name_badge(@member_view.diplomats)
	%a.list-group-item{href: '#'}
		%span.hidden-xs  Recruitment Officer(s)
		%span.visible-xs RO:
		= members_name_badge(@member_view.recruiters)

app/views/clans/home/_stats.haml
.stats-switch.js-switch
	= link_to 'Average', '#clan_home_stats_average_tab', class: 'active'
	= '/'
	= link_to 'Overall', '#clan_home_stats_overall_tab'

- stat_colors = {'Battles' => 'danger', 'Winrate' => 'success', 'Damage' => nil, 'WN8' => 'success', 'Efficiency' => 'warning'}
- stats_average = @stat_view.average_stats
- stats_overall = @stat_view.overall_stats

.tab-content
	.tab-pane.active#clan_home_stats_average_tab
		- stat_colors.each do |name, color|
			.progress.progress-big
				.progress-bar{style: "width: #{stats_average[name.downcase.to_sym][:percentile]}%;", class: color.nil? ? '' : "progress-bar-#{color}"}= name
				.progress-value
					= number_with_delimiter(stats_average[name.downcase.to_sym][:value].round(2))
					- if name == 'Winrate'
						\%
	.tab-pane#clan_home_stats_overall_tab
		- stat_colors.each do |name, color|
			.progress.progress-big
				.progress-bar{style: "width: #{stats_overall[name.downcase.to_sym][:percentile]}%;", class: color.nil? ? '' : "progress-bar-#{color}"}= name
				.progress-value
					= number_with_delimiter(stats_overall[name.downcase.to_sym][:value].round(2))
					- if name == 'Winrate'
						\%

app/views/clans/home/_tanks.haml
.stats-switch.js-switch{role: 'tablist' }
	= link_to '# players', '#clan_home_tanks_player_tab', class: 'active', role: 'tab'
	= '/'
	= link_to '# tanks', '#clan_home_tanks_tank_tab', role: 'tab'

.tab-content
	.tab-pane.active#clan_home_tanks_player_tab
		- player_count = @clan.members.count
		- @tank_view.player_counts.each do |name, count|
			.progress.progress-big
				.progress-bar{style: "width: #{count.to_f/player_count*100}%;"}
					%i.tank-icon{class: "tank-icon-#{name}"}
				.progress-value= count
	.tab-pane#clan_home_tanks_tank_tab
		- tank_count = @tank_view.count
		- @tank_view.tank_counts.each do |name, count|
			.progress.progress-big
				.progress-bar{style: "width: #{count.to_f/tank_count*100*2}%;"}
					%i.tank-icon{class: "tank-icon-#{name}"}
				.progress-value= count

app/views/clans/index.haml
%h1.text-center Top clans

%table.table.table-striped.table-hover
	%thead
		%tr
			%th #
			%th Emblem
			%th Tag
			%th Name
	%tbody
		- @clans.each_with_index do |clan, i|
			%tr.clickable
				%td= link_to (@clans.offset + i + 1), clan
				%td= image_tag Regions.emblem_url(clan.id, '32x32')
				%td= clan.tag
				%td= clan.name

.text-center
	= will_paginate @clans, renderer: BootstrapPagination::Rails

app/views/clans/members.haml
- @locals[:title] += ' - Members'
= render 'clan_top', active: :members

app/views/clans/show.haml
= render 'clan_top', active: :home

.row.ad-container-300x250
	#clan_home.ad-rest
		.row-fluid
			.col-xs-6
				%h3
					Stats
					%small= link_to 'more', '#'
				= render 'clans/home/stats'
			.col-xs-6
				%h3
					Members
					%small= link_to 'more', '#'
				= render 'clans/home/members'
		.row-fluid
			.col-xs-6
				%h3
					Tanks
					%small= link_to 'more', '#'
				= render 'clans/home/tanks'
			.col-xs-6
				%h3
					Changes
					%small= link_to 'more', '#'
				= render 'clans/home/changes'
	.ad-column.hidden-sm.col-padding
		= render 'side_column'

app/views/clans/stats.haml
- @locals[:title] += ' - Stats'
= render 'clan_top', active: :stats

%table.table.table-striped.table-hover
	%thead
		%tr
			%th #
			%th Name
			%th Battles
			%th Win rate
			%th Damage
			%th Frags
			%th WN8
			%th Efficiency
			%th Updated
	%tbody
		- @stat_view.player_stats.each_with_index do |row, i|
			%tr
				%td= i + 1
				%td= link_to row[:name], player_path(row[:id])
				- if row[:battles].present?
					%td= row[:battles]
					%td= "#{row[:winrate].round(2)} %"
					%td= row[:damage].round(2)
					%td= row[:frags].round(2)
					%td= row[:wn8].round(2)
					%td= row[:efficiency].round(2)
					%td= "#{distance_of_time_in_words_to_now(row[:created_at])} ago"
				- else
					%td{colspan: 6} Loading data...

app/views/clans/tanks.haml
- @locals[:title] += ' - Tanks'
= render 'clan_top', active: :tanks

app/views/concerns/clans/index.html.erb
<h1>Concerns::Clans#index</h1>
<p>Find me in app/views/concerns/clans/index.html.erb</p>

app/views/layouts/_nav.haml
%nav.navbar.navbar-default{role: 'navigation'}
	.container
		.navbar-header
			.nav-left-filler
			= link_to root_path, class: 'navbar-brand' do
				= image_tag 'logo-nav.png', alt: 'Main logo'
			%button.navbar-toggle{data:{toggle: 'collapse', target: '#main_nav_collapse'}}
				%span.icon-bar
				%span.icon-bar
				%span.icon-bar

		.navbar-menu
			.nav-search
				%form#nav_search_form.navbar-form.navbar-left{role: 'search', action: search_path, method: 'get'}
					= render 'partials/region_dropdown', class_name: 'navbar-left'
					.form-group
						= text_field_tag :search, params[:search] || '', placeholder: 'Search', class: 'form-control input-sm', id: 'nav_search'
					= hidden_field_tag :region, current_region, id: 'nav_region'
					%button.btn
						%i.glyphicon.glyphicon-search.icon-white
			#main_nav_collapse.navbar-collapse.collapse
				%ul.nav.navbar-nav
					%li{class: nav_item == :clans ? 'active' : ''}
						= link_to 'Clans', clans_path
					%li{class: nav_item == :api ? 'active' : ''}
						= link_to 'API', '#'

app/views/layouts/application.haml
!!!
%html{lang: :en}
	%head
		%title= title
		%meta{content: 'width=device-width, initial-scale=1.0', name: 'viewport'}
		%link{href: 'http://fonts.googleapis.com/css?family=Oswald:400,300,700&subset=latin,latin-ext', rel: 'stylesheet', type: 'text/css'}
		= javascript_include_tag 'application'
		= stylesheet_link_tag 'application'
		= csrf_meta_tags
	%body
		#wrap
			:javascript
				cfg = #{raw @js.to_json}

			= render 'layouts/nav'

			.container
				= yield

			#push

		#footer WoT clan statistics by adikus | 2015

app/views/partials/_region_dropdown.haml
%span.js-region.dropdown.text-left{class: defined?(class_name) ? class_name : ''}
	%a.btn.dropdown-toggle{href: '#', data:{toggle: 'dropdown'}}
		%span.value= current_region_humanized
		%span.caret
	%ul.dropdown-menu{role: 'menu'}
		- Regions::SUPPORTED_REGIONS.each do |region_id, region_name|
			%li{class: region_id == current_region ? 'active' : ''}
				%a{href: "?region=#{region_id}", data: {region: region_id}}= region_name

app/views/players/_nav_tabs.haml
%li{class: active == :home ? 'active' : ''}
	= link_to 'Home', @player
%li{class: active == :stats ? 'active' : ''}
	= link_to 'Stats', @player
%li{class: active == :tanks ? 'active' : ''}
	= link_to 'Tanks', @player
%li{class: active == :changes ? 'active' : ''}
	= link_to 'Changes', @player
	

app/views/players/show.haml
.row.ad-container-300x250
	#player_header.ad-rest.col-padding-left
		%h1= @player.name

		%ul.nav.nav-tabs.hidden-xxs.hidden-xs.hidden-sm
			= render 'nav_tabs', active: :home

	.ad-column
		.ad.float

.row-fluid.visible-xs.visible-sm
	.span12
		%ul.nav.nav-tabs
			= render 'nav_tabs', active: :home

app/views/search/index.haml
%h1 Results #{params[:search].blank? ? '' : "for '#{params[:search]}'"} in #{current_region_humanized} region
- if @locals[:error]
	.alert.alert-danger= @locals[:error]
- else
	%table.table.table-striped.table-hover
		%thead
			%tr
				%th #
				%th Emblem
				%th Tag
				%th Name
		%tbody
			- @clans.each_with_index do |clan, i|
				%tr.clickable
					%td= link_to i, clan_path(clan['clan_id'])
					%td= image_tag clan['emblems']['medium']
					%td= clan['abbreviation']
					%td= clan['name']